theme: jekyll-theme-minimal
title: Santiago Guada's Portfolio
description: Welcome to my Portfolio Website! Here a quick look to the projects I've worked on and to my interests. 
google_analytics: UA-174201803-1
